# Generated by Django 2.2.2 on 2019-06-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190615_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=200, unique=True, verbose_name='email'),
        ),
    ]
